<template><nav class="navbar navbar-dark nav-glass px-3"><button class="btn btn-menu me-2" @click="drawerOpen=true"><i class="bi bi-list"></i></button><router-link class="navbar-brand brand" to="/">18XX</router-link><form class="search-box ms-auto" @submit.prevent="goSearch"><input v-model="keyword" class="search-input" placeholder="搜索影片 / 演员 / 分类"/><button class="search-btn" type="submit"><i class="bi bi-search"></i></button></form></nav><div v-if="drawerOpen" class="drawer-mask" @click="drawerOpen=false"></div><div class="drawer" :class="{open:drawerOpen}"><div class="drawer-header">分类导航<button class="close-btn" @click="drawerOpen=false">×</button></div><div class="drawer-body"><router-link class="nav-item" to="/" @click="drawerOpen=false"><i class="bi bi-house"></i>首页</router-link><router-link v-for="c in classList" :key="c.type_id" class="nav-item" :to="{name:'category',params:{id:c.type_id}}" @click="drawerOpen=false"><i class="bi bi-play-circle"></i>{{c.type_name}}</router-link></div></div></template>
<script setup>
import { ref,onMounted } from 'vue'
import { useRouter } from 'vue-router'
const router=useRouter(),keyword=ref(''),classList=ref([]),drawerOpen=ref(false)
function goSearch(){const wd=keyword.value.trim();if(wd)router.push({name:'search',query:{wd,page:'1'}})}
async function loadClass(){try{const r=await fetch('/class.json');if(r.ok)classList.value=await r.json()}catch{classList.value=[]}}
onMounted(loadClass)
</script>
<style scoped>.nav-glass{background:rgba(10,15,30,.9);border-bottom:1px solid #1e2a44;position:sticky;top:0;z-index:1000}.brand{color:#4da3ff!important;font-weight:800}.btn-menu{border:1px solid #2b6fff;color:#cfe3ff}.search-box{display:flex;background:#0f172a;border:1px solid #1e2a44;border-radius:999px;overflow:hidden}.search-input{border:0;outline:0;background:transparent;color:#fff;padding:6px 12px;width:200px}.search-btn{background:#2b6fff;border:0;color:#fff;padding:6px 12px}.drawer-mask{position:fixed;inset:0;background:rgba(0,0,0,.6);z-index:998}.drawer{position:fixed;top:0;left:0;width:280px;height:100vh;background:#0f172a;border-right:1px solid #1e2a44;transform:translateX(-100%);transition:.25s;z-index:999}.drawer.open{transform:translateX(0)}.drawer-header{display:flex;justify-content:space-between;padding:12px;color:#fff;border-bottom:1px solid #1e2a44}.close-btn{background:0;border:0;color:#fff;font-size:20px}.drawer-body{padding:10px}.nav-item{display:block;padding:10px 12px;margin-bottom:6px;color:#cfe3ff;text-decoration:none;border-radius:8px}.nav-item:hover{background:#1e2a44}</style>
